config/routes.rb
Rails.application.routes.draw do
  resources :contractors
  resources :invoices

  get 'landings/index'

  resource :landings, only: [:new]

  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'clearance/users#new', as: 'sign_up'

  root 'landings#index'

end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  has_many :invoices
  validates_presence_of :name, :street, :zip_code, :city, :nip
end

app/models/examination.rb
class Examination < ActiveRecord::Base
  belongs_to :examinations_list
  has_many :examination_types
end

app/models/examination_type.rb
class ExaminationType < ActiveRecord::Base

end

app/models/examinations_list.rb
class ExaminationsList < ActiveRecord::Base
  has_one :invoice
  has_many :examinations
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_one :contractor
  belongs_to :examinations_list
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :invoices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  def show

  end

  def new
    @contractor = Contractor.new
  end

  def create
    @contractor = Contractor.new(contractor_params)
    if @contractor.save
      redirect_to @contractor, notice: 'Contractor created successfully'
    else
      render 'new'
    end
  end

  def contractor_params
    params.require(:contractor).permit(:name, :street, :zip_code, :city, :nip)
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  before_action :require_login, only: [:new]

  def index
  end

  def new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/elements/_navbar.html.slim
nav.navbar.navbar-inverse role='navigation'
  / Brand and toggle get grouped for better mobile display
  .container
    .navbar-header
      button.navbar-toggle data-target='#navbar-collapse-1' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Medical Invoices', defined?(root_path) ? root_path : '#', class: 'navbar-brand'
    / Collect the nav links, forms, and other content for toggling
    #navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if signed_in?
          li
            span.navbar-text =current_user.email
          li =link_to 'Sign out', sign_out_path, method: :delete
        - else
          li =link_to 'Sign in', sign_in_path

app/views/landings/index.html.slim
.s
  h1 Landings#index
  p Find me in app/views/landings/index.html.erb

app/views/landings/new.html.slim
.page-header
  h1 Add Page

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MedInv
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => 'width=device-width, initial-scale=1', :name => 'viewport'}/
  %body
    = render partial: 'elements/navbar'
    = bootstrap_flash
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title MedInv
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta name='viewport' content='width=device-width, initial-scale=1'
  body
    = render partial: 'elements/navbar'
    .container
      = bootstrap_flash
      = yield

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>